import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'ShopLook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-body-secondary">
        <div>{children}</div>
        </body>
    </html>
  )
}
